services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "18080:18080"
      - "18081:18081"
    networks:
      - wushuang
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: TianXiaWuShuang
    ports:
      - "3306:3306" #端口映射
    volumes:
      - ./mysql-data:/var/lib/mysql # 将数据目录挂在到本地目录以进行持久化
      - ./mysql-init:/docker-entrypoint-initdb.d # 启动脚本
      - ./mysql-conf/my.cnf:/etc/mysql/my.cnf # 配置一下,因为从window的数据库迁移到linux会出问题
    restart: always #崩溃后重启
    networks:
      - wushuang # 指定网络

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass e65K4t8w2
    networks:
      - wushuang
    volumes:
      - ./.redis-data:/data #持久化


  nacos:
    hostname: nacos          # 关键行
    image: nacos/nacos-server:v2.2.0-slim
    container_name: nacos
    ports:
      - "18375:8848"
      - "19375:9848"
      - "9849:9849"

    volumes:
      - ./.nacos-data:/home/nacos/data
    networks:
      - wushuang
    environment:
      - MODE=standalone # 单节点模式启动
      - PREFER_HOST_MODE=hostname # 支持hostname
      - TZ=Asia/Shanghai # 控制时区
networks:
  wushuang:
    driver: bridge  # 指定网络驱动，默认为 bridge