# 应用服务 WEB 访问端口
server:
  port: 9999
  address: 0.0.0.0
#  ssl:
#    enabled: true
#    key-store: classpath:boothttps.jks
#    key-store-type: JKS
#    key-store-password: 123456
spring:
  application:
    name: ComplaintService
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}  # 默认dev，命令行可覆盖

  cloud:
    nacos:
      discovery:
        server-addr: ${wx.nacos.host}:${wx.nacos.port}
        # 强制指定 gRPC 地址
        server-grpc-addr: ${wx.nacos.host}:${wx.nacos.gRPC}
        # 关键配置：告诉Nacos这是HTTPS服务
  #        metadata:
  #          protocol: https

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${wx.datasource.host}:3306/gold?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${wx.datasource.username}
    password: ${wx.datasource.pw}
    hikari:
      # 设置最大连接池大小
      maximum-pool-size: 30
      # 设置最小空闲连接数
      minimum-idle: 10
      # 设置连接池初始化失败时的超时时间
      initialization-fail-timeout: 10000
      # 设置连接池的最大空闲时间
      idle-timeout: 30000
      # 设置连接池中连接的最大生命周期
      max-lifetime: 60000
      # 设置连接池的连接超时时间
      connection-timeout: 30000
      # 设置连接池的最大等待时间
      validation-timeout: 3000
      # 配置连接池验证SQL（根据数据库选择合适的SQL）
      connection-test-query: SELECT 1
      # 设置连接池的池化管理名称
      pool-name: HikariCP

  redis:
    host: ${wx.redis.host}
    port: ${wx.redis.port}
    password: ${wx.redis.password}
    database: ${wx.redis.database}

# 打印 sql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#minio:
#  url: http://127.0.0.1:9000
#  access-key: minioadmin
#  secret-key: minioadmin

hwy:
  obs:
    access-key: HPUAIQZRXY5HY5JNGMVW
    secret-key: haYSyf9xHP2RK4e0eTLOfkRMP9pCq7fot8FQ6d3M
    bucket-name: wushuangok
    end-point: obs.cn-south-1.myhuaweicloud.com


# spring 事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug