wx:
  nacos:
    host: nacos
    port: 8848
    gRPC: 9848

  datasource:
    host: mysql
    username: gold_user
    pw: TianXiaWuShuang

  redis:
    host: redis
    port: 6379
    password: e65K4t8w2
    database: 0

